name: sunmarbella
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006f9d'
    - '#7c91ca'
    - '#f4fcfe'
    - '#5b1a00'
    - '#fea200'
  brandStrength: 0.125
  lightness: 0.27599077578634024
  saturation: 0.375
  rhythmicContrast: 0.8462507021613419
purpose: []
