name: sunmarbella
favicon: null
layout_spectrum: 0.988712849561125
typography_spectrum: 0.6768446839414537
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.06529728160239756
  lightness: 0.27599077578634024
  saturation: 0.10523586440831423
  rhythmicContrast: 0.8462507021613419
purpose: []
