name: sunmarbella
favicon: null
layout_spectrum: 0.68167
typography_spectrum: 0.7527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffb81d'
    - '#137abf'
    - '#ffffff'
    - '#0000ff'
    - '#000000'
  brandStrength: 0.125
  lightness: 0.27599077578634024
  saturation: 0.375
  rhythmicContrast: 0.8462507021613419
purpose: []
